import {nomiarchFeature} from '../components/nomiarch.mjs';
import { services, deliveryModels } from '../data/services.mjs';
import { caseStudies, experienceNotice } from '../data/caseStudies.mjs';
import { architecture } from '../components/architecture.mjs';
import { arrow,icon,sectionHead,serviceCards,caseCards,cta,esc } from '../components/ui.mjs';
export const home={path:'/',title:'Secure Cloud & Platform Engineering in Canada',description:'Innovizion designs, automates and secures Azure, Kubernetes and cloud platforms for government, regulated industries and enterprise teams across Canada.',body:`
<section class="hero dark" id="banner"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="small-rule"></span> Independent engineering. Canadian delivery.</p><h1>Secure cloud.<br><span>Resilient<br class="desktop-break"> platforms.</span></h1><p class="hero-statement">Engineering that holds up in production.</p><p class="hero-description">We design, automate and secure cloud platforms for government, regulated industries and teams with serious infrastructure to run.</p><div class="button-row"><a class="button button-light" href="/contact/">Discuss a Requirement ${arrow}</a><a class="text-link light-link" href="/capabilities/">View Capabilities <span aria-hidden="true">→</span></a></div></div>${architecture()}</div><div class="hero-bottom container"><span>ARCHITECTURE → IMPLEMENTATION → OPERATIONS</span><span>AZURE / KUBERNETES / TERRAFORM / SECURITY / SRE</span></div></section>
<div class="trust-strip"><div class="container"><span>${icon('location',18)} Kingston, Ontario</span><span>Canadian-owned</span><span>Senior-led delivery</span><span>Remote across Canada</span></div></div>
<section class="section" id="one"><div class="container">${sectionHead('01 / What we do','Depth across the<br>platform lifecycle.','From a sound cloud foundation to the way it is secured, released, observed and recovered.',`<a class="text-link" href="/services/">Explore our expertise ${arrow}</a>`)}${serviceCards(services)}</div></section>
<section class="section section-muted"><div class="container why-grid"><div><p class="eyebrow">02 / The Innovizion approach</p><h2>Good architecture<br>has to work<br><em>on Monday morning.</em></h2><p class="lede">We stay close to the engineering. The people making architecture decisions are involved in putting them into practice.</p><a class="text-link" href="/about/">How we work ${arrow}</a></div><div class="principles">${[
['Senior expertise. Direct access.','Work directly with experienced practitioners who can move from design decisions into code, configuration and troubleshooting.'],
['Architecture through operations.','Connect networking, identity, infrastructure as code, pipelines and monitoring with the team’s day-to-day responsibilities.'],
['Reviewable by design.','Make changes repeatable and traceable, with clear documentation and implementation evidence.'],
['Built for recovery.','Treat observability, failure modes and recoverability as architecture requirements from the start.']
].map((p,i)=>`<article><span class="mono">0${i+1}</span><div><h3>${p[0]}</h3><p>${p[1]}</p></div></article>`).join('')}</div></div></section>
<section class="section government-feature dark"><div class="container government-grid"><div><p class="eyebrow">03 / Government & regulated industries</p><h2>When reliability,<br>traceability and<br>security matter.</h2></div><div><p class="lede">Engineering experience across Canadian federal environments, digital identity, financial services and aviation.</p><p>We help translate control requirements into platform design, implementation and remediation evidence, including ITSG-33 / NIST-aligned work, Protected B readiness and security assessment support.</p><div class="button-row"><a class="button button-light" href="/government/">Government & Regulated Industries ${arrow}</a><a class="text-link light-link" href="/capabilities/">Capability statement <span aria-hidden="true">→</span></a></div></div></div><div class="container assurance-strip"><span>Security architecture</span><span>Control implementation</span><span>Assessment support</span><span>Operational readiness</span></div></section>
<section class="section"><div class="container">${sectionHead('04 / Selected experience','Work grounded in<br>real environments.','Experience connecting cloud architecture with delivery in regulated and large enterprise environments.',`<a class="text-link" href="/case-studies/">Explore the work ${arrow}</a>`)}${caseCards(caseStudies)}<p class="experience-note">${experienceNotice}</p></div></section>
<section class="technology-section"><div class="container"><div class="technology-title"><p class="eyebrow">Tools in service of the architecture</p><p>Built around your environment.</p></div><ul class="technology-list"><li>Microsoft Azure</li><li>Kubernetes</li><li>Terraform</li><li>GitHub Actions</li><li>Entra ID</li><li>Dynatrace</li></ul><p class="technology-secondary">Also working across AWS, GCP, Bicep, Azure DevOps, Helm, Prometheus and Grafana.</p></div></section>
<section class="section"><div class="container">${sectionHead('05 / How we engage','The right depth.<br>The right delivery model.','Start with a focused assessment, a defined project or senior expertise embedded in your team.')}<div class="delivery-grid">${deliveryModels.slice(0,4).map((d,i)=>`<article><span class="mono">0${i+1}</span><h3>${d[0]}</h3><p>${d[1]}</p></article>`).join('')}</div><div class="section-tail"><a class="text-link" href="/services/#delivery">See all engagement options ${arrow}</a><span>Clear scope. Practical deliverables. Knowledge that stays with your team.</span></div></div></section>
<section class="philosophy"><div class="container"><p class="eyebrow">Our engineering standard</p><h2>Understand the dependencies.<br>Automate the repeatable.<br><span>Prove the recovery.</span></h2><p>Security, reliability and maintainability belong in the same conversation.</p></div></section>
${nomiarchFeature({compact:true})}
${cta()}`};
