import { createHash } from 'node:crypto';
import { company } from '../config/company.mjs';
import { locales } from '../config/locales.mjs';
import { services } from '../data/services.mjs';
import { esc,wordmark,arrow } from './ui.mjs';
const links=[['Services','/services/'],['Government','/government/'],['Experience','/case-studies/'],['About','/about/']];
export function layout(page,assetVersion){
  const url=company.url+page.path;
  const schema=[{'@type':'Organization','@id':company.url+'/#organization',name:company.legalName,url:company.url,logo:company.url+'/assets/logo.svg',email:company.email,description:company.description,address:{'@type':'PostalAddress',addressLocality:company.city,addressRegion:company.region,addressCountry:'CA'},areaServed:{'@type':'Country',name:'Canada'}},{'@type':'ProfessionalService','@id':company.url+'/#service',name:company.legalName,url:company.url,email:company.email,address:{'@type':'PostalAddress',addressLocality:company.city,addressRegion:company.region,addressCountry:'CA'},areaServed:'Canada',parentOrganization:{'@id':company.url+'/#organization'}}];
  if(page.path!=='/'&&!page.noindex){const names=[{name:'Home',item:company.url+'/'}];if(page.path.startsWith('/services/')&&page.path!=='/services/')names.push({name:'Services',item:company.url+'/services/'});names.push({name:page.crumb||page.title,item:url});schema.push({'@type':'BreadcrumbList',itemListElement:names.map((n,i)=>({'@type':'ListItem',position:i+1,...n}))});}
  if(page.service)schema.push({'@type':'Service',name:page.service.name,description:page.service.summary,provider:{'@id':company.url+'/#organization'},areaServed:'Canada',url});
  const json=JSON.stringify({'@context':'https://schema.org','@graph':schema}).replace(/</g,'\\u003c');
  const hash=createHash('sha256').update(json).digest('base64');
  const csp=`default-src 'self'; script-src 'self' 'sha256-${hash}'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'; upgrade-insecure-requests`;
  const active=href=>page.path===href||(href==='/services/'&&page.path.startsWith(href));
  const t=locales.messages[locales.default];
  return `<!doctype html>
<html lang="${locales.default}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="${esc(csp)}"><meta name="referrer" content="strict-origin-when-cross-origin"><meta name="theme-color" content="#142625">
<title>${esc(page.title)} | Innovizion Inc.</title><meta name="description" content="${esc(page.description)}"><link rel="canonical" href="${url}">${page.noindex?'<meta name="robots" content="noindex, follow">':''}
<meta property="og:type" content="website"><meta property="og:site_name" content="Innovizion Inc."><meta property="og:locale" content="en_CA"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${company.url}/assets/social.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Innovizion — Secure cloud. Resilient platforms."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(page.title)}"><meta name="twitter:description" content="${esc(page.description)}"><meta name="twitter:image" content="${company.url}/assets/social.png"><meta name="twitter:image:alt" content="Innovizion — Secure cloud. Resilient platforms.">
<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css?v=${assetVersion}"><script src="/assets/site.js?v=${assetVersion}" defer></script><script type="application/ld+json">${json}</script></head>
<body${page.path==='/capabilities/'?' class="capabilities-page"':''}><a class="skip-link" href="#main">${t.skip}</a>
<header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Innovizion home">${wordmark}</a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav" type="button"><span>Menu</span><svg width="20" height="20" viewBox="0 0 20 20" aria-hidden="true"><path d="M2 6h16M2 14h16" stroke="currentColor" stroke-width="1.5"/></svg></button><nav class="site-nav" id="site-nav" aria-label="${t.navigation}">${links.map(([name,href])=>`<a href="${href}"${active(href)?' aria-current="'+(page.path===href?'page':'true')+'"':''}>${name}</a>`).join('')}<a class="nav-capabilities" href="/capabilities/"${page.path==='/capabilities/'?' aria-current="page"':''}>Capabilities</a><a class="button button-nav" href="/contact/">Discuss a Requirement ${arrow}</a></nav></div></header>
<main id="main" tabindex="-1">${page.body}</main>
<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="/" aria-label="Innovizion home">${wordmark}</a><p>Secure cloud. Resilient platforms.<br>Engineering that holds up in production.</p><p class="footer-location">Kingston, Ontario · Serving Canada</p><a class="footer-email" href="mailto:${company.email}">${company.email} ${arrow}</a></div><div><h2>Expertise</h2><ul>${services.map(s=>`<li><a href="/services/${s.slug}/">${esc(s.short)}</a></li>`).join('')}</ul></div><div><h2>Innovizion</h2><ul><li><a href="/government/">Government & regulated industries</a></li><li><a href="/case-studies/">Selected experience</a></li><li><a href="/about/">About the company</a></li><li><a href="/capabilities/">Capability statement</a></li><li><a href="/contact/">Discuss a requirement</a></li></ul></div></div><div class="footer-bottom"><span>© 2026 Innovizion Inc.</span><nav aria-label="Legal"><a href="/privacy/">Privacy</a><a href="/legal/">Legal</a><a href="/accessibility/">Accessibility</a></nav><span>Canadian-owned. Engineering-led.</span></div></div></footer></body></html>`;
}
